# Generated by Django 6.1.2 on 2026-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                (
                    "load_weight_lb",
                    models.PositiveIntegerField(
                        help_text="Truck load weight in pounds"
                    ),
                ),
                ("sample_interval_miles", models.PositiveSmallIntegerField(default=25)),
                ("recommended_route_id", models.CharField(blank=True, max_length=50)),
                (
                    "recommended_route_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "recommended_risk_status",
                    models.CharField(blank=True, max_length=50),
                ),
                ("severe_miles", models.FloatField(default=0.0)),
                ("high_miles", models.FloatField(default=0.0)),
                ("average_risk_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Route Audit Log",
                "verbose_name_plural": "Route Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
